name: Deploy NSPK logos to Yandex Object Storage

on:
  push:
    branches: [ main ]
    paths:
      - 'NSPK/**'   # запускать только если меняется что-то в NSPK

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install AWS CLI via pip
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install awscli

      - name: Configure AWS (Yandex Object Storage)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.YC_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.YC_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
          aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
          aws configure set default.region ru-central1

      - name: Upload NSPK svgs to Yandex Object Storage
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.YC_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.YC_SECRET_ACCESS_KEY }}
        run: |
          find NSPK -type f -name "*.svg" -print0 | \
            xargs -0 -n1 -I{} aws s3 cp "{}" "s3://logos-cdn/svg/$(basename "{}")" \
              --endpoint-url https://storage.yandexcloud.net
